### ISSUE TITLE
Need for Speed: Carbon (1.2)

### ISSUE THREAD

**Issue by archeYR** [Mcpg/ros-db#1]
Rating: gold
    Program author: EA Blackbox
    ReactOS version: 0.4.8 build gcc7f704
    Test time: 3rd December 2017
    What works: The whole game seems to work fine.
    What doesn't work: 
    What wasn't tested: Online
    Additional comments: The game needs D3dx9_26.dll library in order to start.

**Comment by Mcpg** [comment]
Alright, thanks! I will add the entry in a couple of minutes. ;)

**Comment by Mcpg** [comment]
Remember to put "program submittion" label on every issue!
