### ISSUE TITLE
foobar2000 (v1.3.17)

### ISSUE THREAD

**Issue by Hacker1245** [Mcpg/ros-db#7]
Rating: Gold
Program author: Peter Pawlowski
ReactOS version: 0.4.8 build g18d6584
Test time: December 10, 2017
What works: Song playback, tagging, visualizations, equalizer
What doesn't work: Everything works.
What wasn't tested: Audio CD playback
Additional comments: Suffers from audio distortion on VirtualBox v5.2.x. To fix that, you need to pause and unpause the music. Suffers from laggy animations (but not always). Sometimes hangs.

**Comment by Mcpg** [comment]
Great, but next time, request application here: https://github.com/ROS-AppDB/AppForm
This repo contains old version of the database; i'm not maintaining it.

**Comment by cernodile** [comment]
Added it in the new database, but yeah, use the new repository next time. :+1:
